---
all: true
dir: '{{.InterfaceDir}}/mocks'
filename: mock_{{.InterfaceName}}.go
pkgname: mocks
recursive: true
packages:
  go.woodpecker-ci.org/autoscaler/providers/hetznercloud/hcapi:
  go.woodpecker-ci.org/autoscaler/engine:
  go.woodpecker-ci.org/autoscaler/server:
