// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/oracle/oci-go-sdk/v65/core"
	mock "github.com/stretchr/testify/mock"
)

// NewMockComputeClient creates a new instance of MockComputeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComputeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComputeClient {
	mock := &MockComputeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockComputeClient is an autogenerated mock type for the ComputeClient type
type MockComputeClient struct {
	mock.Mock
}

type MockComputeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComputeClient) EXPECT() *MockComputeClient_Expecter {
	return &MockComputeClient_Expecter{mock: &_m.Mock}
}

// LaunchInstance provides a mock function for the type MockComputeClient
func (_mock *MockComputeClient) LaunchInstance(ctx context.Context, request core.LaunchInstanceRequest) (core.LaunchInstanceResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for LaunchInstance")
	}

	var r0 core.LaunchInstanceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.LaunchInstanceRequest) (core.LaunchInstanceResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.LaunchInstanceRequest) core.LaunchInstanceResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(core.LaunchInstanceResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.LaunchInstanceRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComputeClient_LaunchInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LaunchInstance'
type MockComputeClient_LaunchInstance_Call struct {
	*mock.Call
}

// LaunchInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - request core.LaunchInstanceRequest
func (_e *MockComputeClient_Expecter) LaunchInstance(ctx any, request any) *MockComputeClient_LaunchInstance_Call {
	return &MockComputeClient_LaunchInstance_Call{Call: _e.mock.On("LaunchInstance", ctx, request)}
}

func (_c *MockComputeClient_LaunchInstance_Call) Run(run func(ctx context.Context, request core.LaunchInstanceRequest)) *MockComputeClient_LaunchInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.LaunchInstanceRequest
		if args[1] != nil {
			arg1 = args[1].(core.LaunchInstanceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComputeClient_LaunchInstance_Call) Return(launchInstanceResponse core.LaunchInstanceResponse, err error) *MockComputeClient_LaunchInstance_Call {
	_c.Call.Return(launchInstanceResponse, err)
	return _c
}

func (_c *MockComputeClient_LaunchInstance_Call) RunAndReturn(run func(ctx context.Context, request core.LaunchInstanceRequest) (core.LaunchInstanceResponse, error)) *MockComputeClient_LaunchInstance_Call {
	_c.Call.Return(run)
	return _c
}

// ListImages provides a mock function for the type MockComputeClient
func (_mock *MockComputeClient) ListImages(ctx context.Context, request core.ListImagesRequest) (core.ListImagesResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ListImages")
	}

	var r0 core.ListImagesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.ListImagesRequest) (core.ListImagesResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.ListImagesRequest) core.ListImagesResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(core.ListImagesResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.ListImagesRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComputeClient_ListImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListImages'
type MockComputeClient_ListImages_Call struct {
	*mock.Call
}

// ListImages is a helper method to define mock.On call
//   - ctx context.Context
//   - request core.ListImagesRequest
func (_e *MockComputeClient_Expecter) ListImages(ctx any, request any) *MockComputeClient_ListImages_Call {
	return &MockComputeClient_ListImages_Call{Call: _e.mock.On("ListImages", ctx, request)}
}

func (_c *MockComputeClient_ListImages_Call) Run(run func(ctx context.Context, request core.ListImagesRequest)) *MockComputeClient_ListImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.ListImagesRequest
		if args[1] != nil {
			arg1 = args[1].(core.ListImagesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComputeClient_ListImages_Call) Return(listImagesResponse core.ListImagesResponse, err error) *MockComputeClient_ListImages_Call {
	_c.Call.Return(listImagesResponse, err)
	return _c
}

func (_c *MockComputeClient_ListImages_Call) RunAndReturn(run func(ctx context.Context, request core.ListImagesRequest) (core.ListImagesResponse, error)) *MockComputeClient_ListImages_Call {
	_c.Call.Return(run)
	return _c
}

// ListInstances provides a mock function for the type MockComputeClient
func (_mock *MockComputeClient) ListInstances(ctx context.Context, request core.ListInstancesRequest) (core.ListInstancesResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ListInstances")
	}

	var r0 core.ListInstancesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.ListInstancesRequest) (core.ListInstancesResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.ListInstancesRequest) core.ListInstancesResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(core.ListInstancesResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.ListInstancesRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComputeClient_ListInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInstances'
type MockComputeClient_ListInstances_Call struct {
	*mock.Call
}

// ListInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - request core.ListInstancesRequest
func (_e *MockComputeClient_Expecter) ListInstances(ctx any, request any) *MockComputeClient_ListInstances_Call {
	return &MockComputeClient_ListInstances_Call{Call: _e.mock.On("ListInstances", ctx, request)}
}

func (_c *MockComputeClient_ListInstances_Call) Run(run func(ctx context.Context, request core.ListInstancesRequest)) *MockComputeClient_ListInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.ListInstancesRequest
		if args[1] != nil {
			arg1 = args[1].(core.ListInstancesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComputeClient_ListInstances_Call) Return(listInstancesResponse core.ListInstancesResponse, err error) *MockComputeClient_ListInstances_Call {
	_c.Call.Return(listInstancesResponse, err)
	return _c
}

func (_c *MockComputeClient_ListInstances_Call) RunAndReturn(run func(ctx context.Context, request core.ListInstancesRequest) (core.ListInstancesResponse, error)) *MockComputeClient_ListInstances_Call {
	_c.Call.Return(run)
	return _c
}

// ListShapes provides a mock function for the type MockComputeClient
func (_mock *MockComputeClient) ListShapes(ctx context.Context, request core.ListShapesRequest) (core.ListShapesResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ListShapes")
	}

	var r0 core.ListShapesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.ListShapesRequest) (core.ListShapesResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.ListShapesRequest) core.ListShapesResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(core.ListShapesResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.ListShapesRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComputeClient_ListShapes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListShapes'
type MockComputeClient_ListShapes_Call struct {
	*mock.Call
}

// ListShapes is a helper method to define mock.On call
//   - ctx context.Context
//   - request core.ListShapesRequest
func (_e *MockComputeClient_Expecter) ListShapes(ctx any, request any) *MockComputeClient_ListShapes_Call {
	return &MockComputeClient_ListShapes_Call{Call: _e.mock.On("ListShapes", ctx, request)}
}

func (_c *MockComputeClient_ListShapes_Call) Run(run func(ctx context.Context, request core.ListShapesRequest)) *MockComputeClient_ListShapes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.ListShapesRequest
		if args[1] != nil {
			arg1 = args[1].(core.ListShapesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComputeClient_ListShapes_Call) Return(listShapesResponse core.ListShapesResponse, err error) *MockComputeClient_ListShapes_Call {
	_c.Call.Return(listShapesResponse, err)
	return _c
}

func (_c *MockComputeClient_ListShapes_Call) RunAndReturn(run func(ctx context.Context, request core.ListShapesRequest) (core.ListShapesResponse, error)) *MockComputeClient_ListShapes_Call {
	_c.Call.Return(run)
	return _c
}

// TerminateInstance provides a mock function for the type MockComputeClient
func (_mock *MockComputeClient) TerminateInstance(ctx context.Context, request core.TerminateInstanceRequest) (core.TerminateInstanceResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for TerminateInstance")
	}

	var r0 core.TerminateInstanceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.TerminateInstanceRequest) (core.TerminateInstanceResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.TerminateInstanceRequest) core.TerminateInstanceResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(core.TerminateInstanceResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.TerminateInstanceRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComputeClient_TerminateInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TerminateInstance'
type MockComputeClient_TerminateInstance_Call struct {
	*mock.Call
}

// TerminateInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - request core.TerminateInstanceRequest
func (_e *MockComputeClient_Expecter) TerminateInstance(ctx any, request any) *MockComputeClient_TerminateInstance_Call {
	return &MockComputeClient_TerminateInstance_Call{Call: _e.mock.On("TerminateInstance", ctx, request)}
}

func (_c *MockComputeClient_TerminateInstance_Call) Run(run func(ctx context.Context, request core.TerminateInstanceRequest)) *MockComputeClient_TerminateInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.TerminateInstanceRequest
		if args[1] != nil {
			arg1 = args[1].(core.TerminateInstanceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComputeClient_TerminateInstance_Call) Return(terminateInstanceResponse core.TerminateInstanceResponse, err error) *MockComputeClient_TerminateInstance_Call {
	_c.Call.Return(terminateInstanceResponse, err)
	return _c
}

func (_c *MockComputeClient_TerminateInstance_Call) RunAndReturn(run func(ctx context.Context, request core.TerminateInstanceRequest) (core.TerminateInstanceResponse, error)) *MockComputeClient_TerminateInstance_Call {
	_c.Call.Return(run)
	return _c
}
