// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/oracle/oci-go-sdk/v65/identity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIdentityClient creates a new instance of MockIdentityClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentityClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentityClient {
	mock := &MockIdentityClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdentityClient is an autogenerated mock type for the IdentityClient type
type MockIdentityClient struct {
	mock.Mock
}

type MockIdentityClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentityClient) EXPECT() *MockIdentityClient_Expecter {
	return &MockIdentityClient_Expecter{mock: &_m.Mock}
}

// ListAvailabilityDomains provides a mock function for the type MockIdentityClient
func (_mock *MockIdentityClient) ListAvailabilityDomains(ctx context.Context, request identity.ListAvailabilityDomainsRequest) (identity.ListAvailabilityDomainsResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailabilityDomains")
	}

	var r0 identity.ListAvailabilityDomainsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, identity.ListAvailabilityDomainsRequest) (identity.ListAvailabilityDomainsResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, identity.ListAvailabilityDomainsRequest) identity.ListAvailabilityDomainsResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(identity.ListAvailabilityDomainsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, identity.ListAvailabilityDomainsRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentityClient_ListAvailabilityDomains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAvailabilityDomains'
type MockIdentityClient_ListAvailabilityDomains_Call struct {
	*mock.Call
}

// ListAvailabilityDomains is a helper method to define mock.On call
//   - ctx context.Context
//   - request identity.ListAvailabilityDomainsRequest
func (_e *MockIdentityClient_Expecter) ListAvailabilityDomains(ctx any, request any) *MockIdentityClient_ListAvailabilityDomains_Call {
	return &MockIdentityClient_ListAvailabilityDomains_Call{Call: _e.mock.On("ListAvailabilityDomains", ctx, request)}
}

func (_c *MockIdentityClient_ListAvailabilityDomains_Call) Run(run func(ctx context.Context, request identity.ListAvailabilityDomainsRequest)) *MockIdentityClient_ListAvailabilityDomains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 identity.ListAvailabilityDomainsRequest
		if args[1] != nil {
			arg1 = args[1].(identity.ListAvailabilityDomainsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdentityClient_ListAvailabilityDomains_Call) Return(listAvailabilityDomainsResponse identity.ListAvailabilityDomainsResponse, err error) *MockIdentityClient_ListAvailabilityDomains_Call {
	_c.Call.Return(listAvailabilityDomainsResponse, err)
	return _c
}

func (_c *MockIdentityClient_ListAvailabilityDomains_Call) RunAndReturn(run func(ctx context.Context, request identity.ListAvailabilityDomainsRequest) (identity.ListAvailabilityDomainsResponse, error)) *MockIdentityClient_ListAvailabilityDomains_Call {
	_c.Call.Return(run)
	return _c
}
