// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	woodpecker "go.woodpecker-ci.org/woodpecker/v3/woodpecker-go/woodpecker"
)

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// DeployAgent provides a mock function with given fields: _a0, _a1
func (_m *MockProvider) DeployAgent(_a0 context.Context, _a1 *woodpecker.Agent) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeployAgent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *woodpecker.Agent) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProvider_DeployAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployAgent'
type MockProvider_DeployAgent_Call struct {
	*mock.Call
}

// DeployAgent is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *woodpecker.Agent
func (_e *MockProvider_Expecter) DeployAgent(_a0 interface{}, _a1 interface{}) *MockProvider_DeployAgent_Call {
	return &MockProvider_DeployAgent_Call{Call: _e.mock.On("DeployAgent", _a0, _a1)}
}

func (_c *MockProvider_DeployAgent_Call) Run(run func(_a0 context.Context, _a1 *woodpecker.Agent)) *MockProvider_DeployAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*woodpecker.Agent))
	})
	return _c
}

func (_c *MockProvider_DeployAgent_Call) Return(_a0 error) *MockProvider_DeployAgent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvider_DeployAgent_Call) RunAndReturn(run func(context.Context, *woodpecker.Agent) error) *MockProvider_DeployAgent_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeployedAgentNames provides a mock function with given fields: _a0
func (_m *MockProvider) ListDeployedAgentNames(_a0 context.Context) ([]string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListDeployedAgentNames")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_ListDeployedAgentNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeployedAgentNames'
type MockProvider_ListDeployedAgentNames_Call struct {
	*mock.Call
}

// ListDeployedAgentNames is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockProvider_Expecter) ListDeployedAgentNames(_a0 interface{}) *MockProvider_ListDeployedAgentNames_Call {
	return &MockProvider_ListDeployedAgentNames_Call{Call: _e.mock.On("ListDeployedAgentNames", _a0)}
}

func (_c *MockProvider_ListDeployedAgentNames_Call) Run(run func(_a0 context.Context)) *MockProvider_ListDeployedAgentNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProvider_ListDeployedAgentNames_Call) Return(_a0 []string, _a1 error) *MockProvider_ListDeployedAgentNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_ListDeployedAgentNames_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockProvider_ListDeployedAgentNames_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAgent provides a mock function with given fields: _a0, _a1
func (_m *MockProvider) RemoveAgent(_a0 context.Context, _a1 *woodpecker.Agent) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAgent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *woodpecker.Agent) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProvider_RemoveAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAgent'
type MockProvider_RemoveAgent_Call struct {
	*mock.Call
}

// RemoveAgent is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *woodpecker.Agent
func (_e *MockProvider_Expecter) RemoveAgent(_a0 interface{}, _a1 interface{}) *MockProvider_RemoveAgent_Call {
	return &MockProvider_RemoveAgent_Call{Call: _e.mock.On("RemoveAgent", _a0, _a1)}
}

func (_c *MockProvider_RemoveAgent_Call) Run(run func(_a0 context.Context, _a1 *woodpecker.Agent)) *MockProvider_RemoveAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*woodpecker.Agent))
	})
	return _c
}

func (_c *MockProvider_RemoveAgent_Call) Return(_a0 error) *MockProvider_RemoveAgent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvider_RemoveAgent_Call) RunAndReturn(run func(context.Context, *woodpecker.Agent) error) *MockProvider_RemoveAgent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
