when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:6.0.2'
  - &repo 'woodpeckerci/autoscaler'
  - &platforms 'linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le'
  - &golang_image 'docker.io/golang:1.25'

steps:
  - name: vendor
    image: *golang_image
    commands:
      - go mod vendor

  - name: dryrun
    image: *buildx_plugin
    settings:
      dockerfile: Dockerfile
      dry_run: true
      repo: *repo
      platforms: *platforms
      tag: test
    when:
      - event: pull_request

  - name: publish-next
    image: *buildx_plugin
    settings:
      dockerfile: Dockerfile
      repo: *repo
      platforms: *platforms
      tag: next
      username: woodpeckerbot
      password:
        from_secret: docker_password
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  - name: publish-tag
    image: *buildx_plugin
    settings:
      dockerfile: Dockerfile
      repo: *repo
      platforms: *platforms
      tag: [latest, '${CI_COMMIT_TAG}']
      username: woodpeckerbot
      password:
        from_secret: docker_password
    when:
      event: tag
