when:
  event: push
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  release:
    image: woodpeckerci/plugin-ready-release-go:0.7.0
    pull: true
    settings:
      git_email: woodpecker-bot@obermui.de
      github_token:
        from_secret: GITHUB_TOKEN
