when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
  - event: pull_request_metadata
    evaluate: 'CI_COMMIT_PULL_REQUEST_LABELS contains "build_pr_images"'

variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:6.1.1'
  - &buildx_settings
    buildkit_oci_max_parallelism: 1
    dockerfile: docker/Dockerfile
    repo: 'woodpeckerci/autoscaler'
    platforms: 'linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le'
  - &golang_image 'docker.io/golang:1.27'

steps:
  - name: vendor
    image: *golang_image
    commands:
      - go mod vendor

  - name: dryrun
    image: *buildx_plugin
    settings:
      <<: *buildx_settings
      dry_run: true
      tag: test
    when:
      - event: pull_request
        evaluate: 'not (CI_COMMIT_PULL_REQUEST_LABELS contains "build_pr_images")'

  - name: publish-preview
    image: *buildx_plugin
    settings:
      <<: *buildx_settings
      tag: pull_${CI_COMMIT_PULL_REQUEST}
      username: woodpeckerbot
      password:
        from_secret: docker_password
    when:
      - event: [pull_request, pull_request_metadata]
        evaluate: 'CI_COMMIT_PULL_REQUEST_LABELS contains "build_pr_images"'

  - name: publish-next
    image: *buildx_plugin
    settings:
      <<: *buildx_settings
      tag: next
      username: woodpeckerbot
      password:
        from_secret: docker_password
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  - name: publish-tag
    image: *buildx_plugin
    settings:
      <<: *buildx_settings
      tag: [latest, '${CI_COMMIT_TAG}']
      username: woodpeckerbot
      password:
        from_secret: docker_password
    when:
      event: tag
