when:
  event: push
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: release
    image: docker.io/woodpeckerci/plugin-ready-release-go:3.4.0
    pull: true
    settings:
      git_email: woodpecker-bot@obermui.de
      github_token:
        from_secret: GITHUB_TOKEN
