when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  dryrun:
    image: woodpeckerci/plugin-docker-buildx:3.2.0
    settings:
      dockerfile: Dockerfile
      dry_run: true
      repo: woodpeckerci/autoscaler
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
      tag: test
    when:
      event: pull_request

  publish-next:
    image: woodpeckerci/plugin-docker-buildx:3.2.0
    settings:
      dockerfile: Dockerfile
      repo: woodpeckerci/autoscaler
      platforms: linux/arm/v7,linux/arm64,linux/amd64,linux/ppc64le
      tag: next
      username: woodpeckerbot
    secrets: [docker_password]
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  publish-tag:
    image: woodpeckerci/plugin-docker-buildx:3.2.0
    settings:
      dockerfile: Dockerfile
      repo: woodpeckerci/autoscaler
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
      tag: [latest, "${CI_COMMIT_TAG}"]
      username: woodpeckerbot
    secrets: [docker_password]
    when:
      event: tag
