when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  dryrun:
    image: woodpeckerci/plugin-docker-buildx:2.2.0@sha256:6e95efac78f04d45c4177c07489bc01cb6dc5ae6b39f723edd42d5d695b6f2be
    settings:
      dockerfile: Containerfile
      dry_run: true
      repo: woodpeckerci/autoscaler
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
      tag: test
    when:
      event: pull_request

  publish-next:
    image: woodpeckerci/plugin-docker-buildx:2.2.0@sha256:6e95efac78f04d45c4177c07489bc01cb6dc5ae6b39f723edd42d5d695b6f2be
    settings:
      dockerfile: Containerfile
      repo: woodpeckerci/autoscaler
      platforms: linux/arm/v7,linux/arm64,linux/amd64,linux/ppc64le
      tag: next
    secrets: [docker_username, docker_password]
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  publish-tag:
    image: woodpeckerci/plugin-docker-buildx:2.2.0@sha256:6e95efac78f04d45c4177c07489bc01cb6dc5ae6b39f723edd42d5d695b6f2be
    settings:
      dockerfile: Containerfile
      repo: woodpeckerci/autoscaler
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
      tag: [latest, "${CI_COMMIT_TAG}"]
    secrets: [docker_username, docker_password]
    when:
      event: tag
