when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - renovate/*

variables:
  - &buildx-plugin 'woodpeckerci/plugin-docker-buildx:4.2.0'
  - &repo 'woodpeckerci/autoscaler'
  - &platforms 'linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le'

steps:
  dryrun:
    image: *buildx-plugin
    settings:
      dockerfile: Dockerfile
      dry_run: true
      repo: *repo
      platforms: *platforms
      tag: test
    when:
      - event: pull_request
      - event: push
        branch:
          - renovate/*

  publish-next:
    image: *buildx-plugin
    settings:
      dockerfile: Dockerfile
      repo: *repo
      platforms: *platforms
      tag: next
      username: woodpeckerbot
      password:
        from_secret: docker_password
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push

  publish-tag:
    image: *buildx-plugin
    settings:
      dockerfile: Dockerfile
      repo: *repo
      platforms: *platforms
      tag: [latest, '${CI_COMMIT_TAG}']
      username: woodpeckerbot
      password:
        from_secret: docker_password
    when:
      event: tag
