when:
  - event: pull_request

variables:
  - &golang_image 'golang:1.24'
  - &when
    - path: &when_path # related config files
        - '.woodpecker/test.yml'
        - '.golangci.yml'
        # go source code
        - '**/*.go'
        - 'go.*'
        # schema changes
        - 'pipeline/schema/**'
        # tools updates
        - Makefile
      branch:
        exclude: ${CI_REPO_DEFAULT_BRANCH}
      event: push
    - path: *when_path
      event: [pull_request, tag, deployment]

steps:
  lint:
    image: *golang_image
    depends_on: []
    commands:
      - make lint
    when: *when

  lint-editorconfig:
    image: mstruebing/editorconfig-checker:v3.2.1
    depends_on: []

  test:
    image: *golang_image
    depends_on: []
    commands:
      - make test
    when: *when
