when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &golang_image "golang:1.21.3@sha256:24a09375a6216764a3eda6a25490a88ac178b5fcb9511d59d0da5ebf9e496474"
  - &when
    - path: &when_path # related config files
        - ".woodpecker/test.yml"
        - ".golangci.yml"
        # go source code
        - "**/*.go"
        - "go.*"
        # schema changes
        - "pipeline/schema/**"
      branch:
        exclude: ${CI_REPO_DEFAULT_BRANCH}
      event: push
    - path: *when_path
      event: [pull_request, tag, deployment]

steps:
  lint:
    image: *golang_image
    group: test
    commands:
      - make lint
    when: *when

  lint-editorconfig:
    image: mstruebing/editorconfig-checker:2.7.2@sha256:51036dbf4e04da68b5be60f9b3f4c9480e801366b6a2aa2773c7746155cbe3df
    group: test

  test:
    image: *golang_image
    group: test
    commands:
      - make test
    when: *when
